name = "worker-example"
type = "webpack"
webpack_config = "webpack.config.js"
kv_namespaces = [ "KV_NAMESPACE_EXAMPLE" ]
environment_variables= [ "SECRET_EXAMPLE" ]
recommended_route = "*example.com/test"